version: '3'

services:
  postgresql:
    image: postgres:9.4
    container_name: inquiredb
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "inquire"
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres
  python:
    build: ./inquire-app/
    container_name: inquire
    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - "./inquire-app:/code"
    ports:
      - "8001:8001"
    depends_on:
      - postgresql